apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: nicehash
  annotations:
    deprecated.daemonset.template.generation: '4'
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"apps/v1","kind":"DaemonSet","metadata":{"annotations":{},"name":"mining-pod","namespace":"nicehash"},"spec":{"selector":{"matchLabels":{"app":"mining-pod"}},"template":{"metadata":{"labels":{"app":"mining-pod"}},"spec":{"containers":[{"image":"dockerhubnh/nicehash:latest","name":"mining-container"}],"priorityClassName":"low-priority","runtimeClassName":"nvidia","tolerations":[{"effect":"NoExecute","key":"mining-pod","operator":"Exists"}]}}}}
  creationTimestamp: '2024-03-24T21:21:45Z'
  generation: 4
  managedFields:
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:deprecated.daemonset.template.generation: {}
            f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:spec:
          f:revisionHistoryLimit: {}
          f:selector: {}
          f:template:
            f:metadata:
              f:labels:
                .: {}
                f:app: {}
            f:spec:
              f:containers:
                k:{"name":"mining-container"}:
                  .: {}
                  f:image: {}
                  f:imagePullPolicy: {}
                  f:name: {}
                  f:resources: {}
                  f:terminationMessagePath: {}
                  f:terminationMessagePolicy: {}
              f:dnsPolicy: {}
              f:priorityClassName: {}
              f:restartPolicy: {}
              f:runtimeClassName: {}
              f:schedulerName: {}
              f:securityContext: {}
              f:terminationGracePeriodSeconds: {}
              f:tolerations: {}
          f:updateStrategy:
            f:rollingUpdate:
              .: {}
              f:maxSurge: {}
              f:maxUnavailable: {}
            f:type: {}
      manager: kubectl-client-side-apply
      operation: Update
      time: '2024-03-24T21:21:45Z'
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:template:
            f:metadata:
              f:annotations:
                .: {}
                f:cattle.io/timestamp: {}
              f:namespace: {}
            f:spec:
              f:containers:
                k:{"name":"mining-container"}:
                  f:env:
                    .: {}
                    k:{"name":"MINING_ADDRESS"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"MINING_WORKER_NAME"}:
                      .: {}
                      f:name: {}
                      f:valueFrom:
                        .: {}
                        f:fieldRef: {}
                    k:{"name":"NVIDIA_VISIBLE_DEVICES"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                  f:resources:
                    f:limits:
                      .: {}
                      f:nvidia.com/gpu: {}
                    f:requests:
                      .: {}
                      f:nvidia.com/gpu: {}
      manager: agent
      operation: Update
      time: '2024-03-24T21:37:32Z'
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:currentNumberScheduled: {}
          f:desiredNumberScheduled: {}
          f:numberAvailable: {}
          f:numberReady: {}
          f:numberUnavailable: {}
          f:observedGeneration: {}
          f:updatedNumberScheduled: {}
      manager: k3s
      operation: Update
      subresource: status
      time: '2024-03-24T21:37:37Z'
  name: mining-pod
  namespace: default
  resourceVersion: '22198'
  uid: eac2cb8d-6ddf-4fa0-b338-25b4fa5a822c
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mining-pod
  template:
    metadata:
      annotations:
        cattle.io/timestamp: '2024-03-24T21:37:33Z'
      creationTimestamp: null
      labels:
        app: mining-pod
      namespace: default
    spec:
      containers:
        - env:
            - name: MINING_WORKER_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: MINING_ADDRESS
              value: bc1qddzh2765dfrrn4t2k9ff9n7zkzfqzw9lytmjp8
            - name: NVIDIA_VISIBLE_DEVICES
              value: all
          image: dockerhubnh/nicehash:latest
          imagePullPolicy: Always
          name: mining-container
          resources:
            limits:
              nvidia.com/gpu: '2'
            requests:
              nvidia.com/gpu: '2'
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      priorityClassName: low-priority
      restartPolicy: Always
      runtimeClassName: nvidia
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
        - effect: NoExecute
          key: mining-pod
          operator: Exists
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate