apiVersion: v1
kind: Service
metadata:
  name: nvidia-dcgm-exporter
  namespace: gpu-operator
spec:
  ports:
    - port: 9400
      targetPort: 9400
      name: metrics
  selector:
    app: nvidia-dcgm-exporter
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nvidia-dcgm-exporter
  namespace: cattle-monitoring-system # Or the namespace where your Prometheus Operator is looking for ServiceMonitors
spec:
  jobLabel: nvidia-dcgm-exporter
  selector:
    matchLabels:
      app: nvidia-dcgm-exporter
  namespaceSelector:
    matchNames:
      - gpu-operator
  endpoints:
    - port: metrics
      interval: 15s